name: syntax

on: push

jobs:
  task1:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: 3.7
    - run: echo It works
    - run: echo Made by Andrei Radu
    - run: | 
            if [ "$(python add.py 1 2)" != "3" ]
            then 
                exit 1 
            fi
            if [ "$(python add.py 2 5)" != "7" ]
            then 
                exit 1 
            fi
            if [ "$(python add.py 6 2)" != "8" ]
            then 
                exit 1 
            fi
            if [ "$(python add.py 1 2)" = "3" ]
            then 
                exit 0 
            fi
        