name: syntax

on: push

jobs:
  task1:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
          python-version: 3.7
    - run: echo It works
    - run: echo Made by Andrei Radu
    - run: | if [ $("python add 1 2") != "3" ] 
          exit 1 
        fi


    - run: python3 add.py 2 5 # test 2
    - run: python3 add.py 3 4 # test 3
    - run: python3 add.py 1 9 # test 4
    - run: python3 add.py 2 10 # test 5